[app]
name = "nuit-multiplatform-example"
stylized-name = "Nuit Multiplatform Example"
identifier = "multiplatform.nuit.example.com"
template-pack = "winit"

[apple]
development-team = "$(DEVELOPMENT_TEAM)"
